"use client";

import { useState, useRef } from "react";
import { EditSidebar } from "@/components/EditSidebar";
import { PreviewPane } from "@/components/PreviewPane";
import { TopNav } from "@/components/TopNav";
import { FormattingToolbar } from "@/components/FormattingToolbar";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";

export interface DocumentItem {
  id: string;
  indexText?: string;
  heading: string;
  description: string;
  isMemoEnabled: boolean;
  textRows: number;
}

export type FloatingElementType = 'image' | 'shape' | 'text';

export interface FloatingElement {
  id: string;
  type: FloatingElementType;
  x: number;
  y: number;
  width: number;
  height: number;
  content: string; // Base64 image data, shape type, or text html
  shapeType?: 'rect' | 'circle'; // if type === 'shape'
  // style properties can be added here
  backgroundColor?: string;
  borderColor?: string;
  borderWidth?: number;
  borderRadius?: number;
  textColor?: string;
}

export interface DocumentState {
  title: string;
  date: string;
  attendees: string;
  items: DocumentItem[];
  floatingElements: FloatingElement[];
  orientation: "portrait" | "landscape";
  padding: number;
  isAttendeesVisible: boolean;
}

export default function Home() {
  // 1. Centralized State Management
  const [documentState, setDocumentState] = useState<DocumentState>({
    title: "",
    date: "",
    attendees: "",
    items: [],
    floatingElements: [],
    orientation: "portrait",
    padding: 24,
    isAttendeesVisible: true,
  });

  // 2. UI View State
  const [isEditorOpen, setIsEditorOpen] = useState(false);

  // Passed down to TopNav to control editor sidebar via "Edit" button
  const toggleEditor = () => setIsEditorOpen(prev => !prev);

  // Handlers for printing and clearing
  const handlePrint = () => window.print();
  const handleClear = () => {
    if (window.confirm("画面のすべての内容をクリアしますか？この操作は元に戻せません。")) {
      setDocumentState({
        title: "",
        date: "",
        attendees: "",
        items: [],
        floatingElements: [],
        orientation: "portrait",
        padding: 24,
        isAttendeesVisible: true,
      });
    }
  };

  const handleSavePdf = async () => {
    const el = document.getElementById("pdf-content");
    if (!el) return;

    try {
      // 1. Generate PDF from DOM with oklab/lab color workaround
      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        onclone: (clonedDoc) => {
          // html2canvas parser crashes on oklab/lab colors generated by Tailwind v4.
          // We iterate over all elements in the clone and replace oklab/lab with rgb.
          // A simple approach: remove the standard Tailwind variable injections or replace 
          // computed styles that use them.
          const elements = clonedDoc.querySelectorAll("*");
          const colorProps = ['color', 'backgroundColor', 'borderColor', 'outlineColor', 'textDecorationColor'];

          elements.forEach((node) => {
            const el = node as HTMLElement;
            // First check inline styles and replace literal oklab/lab strings
            if (el.getAttribute('style')?.includes('lab')) {
              const styleStr = el.getAttribute('style') || "";
              // Remove or replace unsupported color strings in inline style 
              // (Very basic fallback: replacing with a safe color if matching)
              const safeStyle = styleStr.replace(/oklab\([^)]+\)/g, 'rgb(0, 0, 0)')
                .replace(/lab\([^)]+\)/g, 'rgb(0, 0, 0)');
              if (safeStyle !== styleStr) {
                el.setAttribute('style', safeStyle);
              }
            }
            // For computed styles from classes (Tailwind variables), 
            // html2canvas parses the computed style. If a variable resolves to oklab, it crashes.
            // We force explicit rgb styles on elements taking the colors from var(--color-*)
            const computed = window.getComputedStyle(el);
            colorProps.forEach(prop => {
              const val = computed.getPropertyValue(prop);
              if (val && (val.includes('oklab') || val.includes('lab('))) {
                // Force it to a safe fallback directly on the clone
                (el.style as any)[prop] = 'rgb(0, 0, 0)';
              }
            });
          });
        }
      });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: documentState.orientation,
        unit: "mm",
        format: "a4"
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);

      // 2. Extract raw PDF blob
      const pdfBlob = pdf.output("blob");

      // 3. Append JSON metadata at the end of the blob
      const metadataStr = `\n---PDFAPP_DATA---\n${JSON.stringify(documentState)}`;
      const metadataBlob = new Blob([metadataStr], { type: "text/plain" });

      // Combine them
      const combinedBlob = new Blob([pdfBlob, metadataBlob], { type: "application/pdf" });

      // 4. Download
      const url = URL.createObjectURL(combinedBlob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${documentState.title || "document"}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error("PDF generation failed", e);
      alert("PDFの生成に失敗しました。");
    }
  };

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleLoadPdf = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      const text = await file.text();
      const parts = text.split("---PDFAPP_DATA---\n");
      if (parts.length > 1) {
        const jsonStr = parts[parts.length - 1];
        const state = JSON.parse(jsonStr) as DocumentState;
        if (state && typeof state === "object" && "items" in state) {
          // Compatibility for older saves without floatingElements
          if (!state.floatingElements) state.floatingElements = [];

          setDocumentState(state);
          return;
        }
      }
      alert("このファイルには編集用データが含まれていないか、破損しています。");
    } catch (e) {
      console.error("Failed to load PDF data", e);
      alert("ファイルの読み込みに失敗しました。");
    } finally {
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  };

  // --- Insert Floating Elements ---
  const imageInputRef = useRef<HTMLInputElement>(null);

  const handleInsertImageClick = () => {
    imageInputRef.current?.click();
  };

  const handleImageFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const base64 = event.target?.result as string;

      // Get an image object to check dimensions
      const img = new Image();
      img.onload = () => {
        let w = img.width;
        let h = img.height;
        // Scale down if too large (e.g., max 300px width initially)
        if (w > 300) {
          h = Math.round((300 / w) * h);
          w = 300;
        }

        setDocumentState(prev => ({
          ...prev,
          floatingElements: [
            ...prev.floatingElements,
            {
              id: crypto.randomUUID(),
              type: 'image',
              x: 50, // Initial dropped coords
              y: 50,
              width: w,
              height: h,
              content: base64
            }
          ]
        }));
      };
      img.src = base64;
    };
    reader.readAsDataURL(file);

    if (imageInputRef.current) imageInputRef.current.value = "";
  };

  const handleInsertShape = () => {
    setDocumentState(prev => ({
      ...prev,
      floatingElements: [
        ...prev.floatingElements,
        {
          id: crypto.randomUUID(),
          type: 'shape',
          x: 100,
          y: 100,
          width: 100,
          height: 100,
          content: '',
          shapeType: 'rect',
          backgroundColor: '#3b82f640', // light blue semi transparent
          borderColor: '#3b82f6',
          borderWidth: 2
        }
      ]
    }));
  };

  const handleInsertText = () => {
    setDocumentState(prev => ({
      ...prev,
      floatingElements: [
        ...prev.floatingElements,
        {
          id: crypto.randomUUID(),
          type: 'text',
          x: 100,
          y: 150,
          width: 200,
          height: 80,
          content: 'テキスト',
          textColor: '#000000',
        }
      ]
    }));
  };

  return (
    <main className="min-h-screen bg-[#0a0a0c] selection:bg-[#e8af48]/30 selection:text-[#e8af48] flex flex-col font-sans overflow-hidden">
      {/* Hidden file input for loading PDFs */}
      <input
        type="file"
        accept=".pdf"
        ref={fileInputRef}
        onChange={handleFileChange}
        className="hidden"
      />
      {/* Hidden file input for inserting images */}
      <input
        type="file"
        accept="image/*"
        ref={imageInputRef}
        onChange={handleImageFileChange}
        className="hidden"
      />

      {/* Top Floating Tools */}
      <TopNav
        isEditorOpen={isEditorOpen}
        onToggleEditor={() => setIsEditorOpen(!isEditorOpen)}
        onPrint={handlePrint}
        onClear={handleClear}
        onSavePdf={handleSavePdf}
        onLoadPdf={handleLoadPdf}
        onInsertImage={handleInsertImageClick}
        onInsertShape={handleInsertShape}
        onInsertText={handleInsertText}
      />

      <div className="fixed top-3 left-1/2 -translate-x-1/2 z-50">
        <FormattingToolbar />
      </div>

      {/* Main Workspace Layout - Fixed height to viewport to prevent full page scroll */}
      <div className="flex-1 flex w-full relative h-[calc(100vh-80px)] mt-[80px] overflow-hidden">

        {/* Background effects for the workspace */}
        <div className="absolute inset-0 pointer-events-none opacity-50 bg-[radial-gradient(circle_at_50%_50%,rgba(255,255,255,0.02)_0%,transparent_100%)] z-0" />

        {/* Left Side: Editor Sidebar (Absolute positioning to not squeeze the preview) */}
        <div
          className={`absolute left-0 top-0 h-full flex-shrink-0 transition-all duration-500 ease-[cubic-bezier(0.34,1.2,0.64,1)] z-40 ${isEditorOpen ? "w-[360px] translate-x-0 opacity-100" : "w-0 -translate-x-full opacity-0 overflow-hidden"
            }`}
        >
          {/* Override pt-[80px] inside EditSidebar by passing a custom class or removing it since we now have mt-[80px] on the parent. Wait, EditSidebar is inside this absolute div. Let's make this div fixed to top:80px or just remove the pt-80 from EditSidebar and handle it here. For simplicity we will remove `pt-[80px]` from EditSidebar.tsx as well in the next step, but here we adjust the layout. */}
          <EditSidebar
            documentState={documentState}
            setDocumentState={setDocumentState}
            onClose={() => setIsEditorOpen(false)}
          />
        </div>

        {/* Right Side: Live Preview Pane (Takes full width always, centered, independently scrollable) */}
        <div className={`flex-1 h-full relative z-0 flex items-center justify-center p-8 overflow-y-auto overflow-x-hidden bg-black/20 transition-all duration-500 ${isEditorOpen ? "pl-[380px]" : ""}`}>
          <PreviewPane documentState={documentState} setDocumentState={setDocumentState} />
        </div>
      </div>
    </main>
  );
}
